### ISSUE TITLE
[CI] Add configuration for PostgreSQL in CircleCI

### ISSUE THREAD

**Issue by wo0dyn** [peopledoc/django-formidable#161]
It would be nice to add configuration for PostgreSQL in CircleCI settings so we can check that SQL performances are OK against a PostgreSQL database as well.

Ideally we can keep both SQLite and PostgreSQL.

**Comment by brunobord** [comment]
found this: https://discuss.circleci.com/t/django-postgresql-and-circleci/15032/3

**Comment by wo0dyn** [comment]
It's _never_ too late. 😉
